apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    Project: roboshop
    component: frontend
    tier: frontend
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: frontend
      tier: frontend
  template:
    metadata:
      labels:
        Project: roboshop
        component: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: akhilln/frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend
---
apiVersion: v1 
kind: Service
metadata:
  name: frontend
spec:
  selector:
    Project: roboshop
    component: frontend
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
