apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    Project: roboshop
    component: frontend
    tier: frontend
  namespace: roboshop
spec:
  replicas: 2
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      Project: roboshop
      component: frontend
      tier: frontend
  template:
    metadata:
      labels:
        Project: roboshop
        component: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: akhilln/frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1 
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    Project: roboshop
    component: frontend
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
