apiVersion: v1 
kind: ConfigMap
metadata:
  name: payment
  labels:
    Project: roboshop
    component: payment
    tier: backend
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user" 
  USER_PORT: "8080" 
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    Project: roboshop
    component: payment
    tier: backend
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: payment
      tier: backend
  template:
    metadata:
      labels:
        Project: roboshop
        component: payment
        tier: backend
    spec:
      containers:
      - name: payment
        image: akhilln/payment:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: payment
---
apiVersion: v1 
kind: Service
metadata:
  name: payment
spec:
  selector:
    Project: roboshop
    component: payment
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
