apiVersion: v1 
kind: ConfigMap
metadata:
  name: cart
  labels:
    Project: roboshop
    component: cart
    tier: backend
  namespace: roboshop
data:
  REDIS_HOST: redis
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    Project: roboshop
    component: cart
    tier: backend
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: cart
      tier: backend
  template:
    metadata:
      labels:
        Project: roboshop
        component: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: akhilln/cart:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1 
kind: Service
metadata:
  name: cart
spec:
  selector:
    Project: roboshop
    component: cart
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
