apiVersion: v1 
kind: ConfigMap
metadata:
  name: shipping
  labels:
    Project: roboshop
    component: shipping
    tier: backend
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    Project: roboshop
    component: shipping
    tier: backend
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: shipping
      tier: backend
  template:
    metadata:
      labels:
        Project: roboshop
        component: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: akhilln/shipping:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1 
kind: Service
metadata:
  name: shipping
spec:
  selector:
    Project: roboshop
    component: shipping
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
