apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    Project: roboshop
    component: rabbitmq
    tier: db 
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: rabbitmq
      tier: db
  template:
    metadata:
      labels:
        Project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    Project: roboshop
    component: rabbitmq
    tier: db
  port:
  - protocol: TCP
    port: 5672
    targetPort: 5672