apiVersion: v1 
kind: ConfigMap
metadata:
  name: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: "roboshop"
  RABBITMQ_DEFAULT_PASS: "roboshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    Project: roboshop
    component: rabbitmq
    tier: db 
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: rabbitmq
      tier: db
  template:
    metadata:
      labels:
        Project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13.0-alpine
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: rabbitmq
        ports:
        - containerPort: 5672
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    Project: roboshop
    component: rabbitmq
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672