apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    Project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        Project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: akhilln/mongodb:v1
        containerPort: 27017
---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    Project: roboshop
    component: mongodb
    tier: db
  port: 27017
  targetPort: 27017
