apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    Project: roboshop
    component: mysql
    tier: db 
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        Project: roboshop
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: akhilln/mysql:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 40
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
spec:
  selector:
    Project: roboshop
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # contaner port
      