apiVersion: v1 
kind: ConfigMap
metadata:
  name: catalogue
  labels:
    Project: roboshop
    component: catalogue
    tier: backend
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    Project: roboshop
    component: catalogue
    tier: backend
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: catalogue
      tier: backend
  template:
    metadata:
      labels:
        Project: roboshop
        component: catalogue
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: akhilln/catalogue:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1 
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    Project: roboshop
    component: catalogue
    tier: backend
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080