apiVersion: v1 
kind: ConfigMap
metadata:
  name: user
  labels:
    Project: roboshop
    component: user
    tier: backend
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    Project: roboshop
    component: user
    tier: backend
  namespace: roboshop
spec:
  replicas: 2
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      Project: roboshop
      component: user
      tier: backend
  template:
    metadata:
      labels:
        Project: roboshop
        component: user
        tier: backend
    spec:
      containers:
      - name: user
        image: akhilln/user:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: user
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          failureThreshold: 3
          periodSeconds: 10
---
apiVersion: v1 
kind: Service
metadata:
  name: user
spec:
  selector:
    Project: roboshop
    component: user
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
