apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    Project: roboshop
    component: redis
    tier: db 
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      Project: roboshop
      component: redis
      tier: db
  template:
    metadata:
      labels:
        Project: roboshop
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: akhilln/redis:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
---
apiVersion: v1 
kind: Service
metadata:
  name: redis
spec:
  selector:
    Project: roboshop
    component: redis
    tier: db
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379